"use client";

import { useState, type FormEvent } from "react";
import { ArrowDown, ArrowUpRight, Check, Minus, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import "./vistall-home.css";

const paymentUrl = "https://mpago.la/26Q1m2a";
const contactEmail = "contato@vistall.com.br";

function Asterisk({ className = "" }: { className?: string }) {
  return <svg className={className} viewBox="0 0 100 100" fill="none" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round" aria-hidden="true"><path d="M50 10v80M10 50h80M21.7 21.7l56.6 56.6M78.3 21.7 21.7 78.3" /></svg>;
}

function Brand() { return <span className="v-brand" aria-label="Vistall">Vistall<span>.</span></span>; }

const services = [
  { number: "01 / REVISÃO", tag: "Para sites que já existem", title: "Revisão & ajustes pontuais", description: "Um olhar para a página inicial, a leitura no celular e o caminho até o contato. Depois, combinamos até três melhorias possíveis de aplicar.", features: ["Uma página avaliada", "Até três ajustes aprovados", "Resumo do que mudou"], price: "R$ 250", note: "valor fixo por revisão", action: "Solicitar revisão", href: "#contato" },
  { number: "02 / CRIAÇÃO", tag: "Do zero à publicação", title: "Sites sob medida", description: "Páginas de apresentação, portfólios e sites institucionais feitos para explicar seu negócio com clareza e funcionar bem no celular.", features: ["Estrutura e visual próprios", "Layout responsivo", "Publicação combinada no escopo"], price: "Sob consulta", note: "proposta antes de contratar", action: "Orçar meu site", href: `mailto:${contactEmail}?subject=Or%C3%A7amento%20de%20site` },
  { number: "03 / SISTEMAS", tag: "Ferramentas para sua operação", title: "Apps & sistemas web", description: "Painéis, formulários e fluxos digitais para uma necessidade concreta do seu trabalho. O projeto começa com uma conversa sobre o que precisa funcionar.", features: ["Escopo definido em conjunto", "Interface pensada para o uso", "Valor e entrega por proposta"], price: "Sob consulta", note: "projeto com escopo próprio", action: "Descrever meu sistema", href: `mailto:${contactEmail}?subject=Or%C3%A7amento%20de%20sistema%20web` },
];

const steps = [
  { title: "Um olhar atento.", text: "Revisamos a página inicial: mensagem, leitura no celular e caminho até o contato. A checagem automática ajuda a apontar itens que precisam de confirmação humana." },
  { title: "Um escopo combinado.", text: "Indicamos até três ajustes viáveis. Você aprova as mudanças e fornece o acesso necessário antes de qualquer edição no seu site." },
  { title: "Você vê o que mudou.", text: "Aplicamos os ajustes aprovados e entregamos um resumo. Melhoramos a página; vendas ou posições no Google dependem de fatores externos." },
];

export default function VistallHome() {
  const [checked, setChecked] = useState(false);
  const [state, setState] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const [error, setError] = useState("");
  const [demo, setDemo] = useState("after");
  const [openStep, setOpenStep] = useState<number | null>(0);
  const improved = demo === "after";

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!checked || state === "sending") return;
    const form = event.currentTarget;
    const data = new FormData(form);
    setState("sending"); setError("");
    try {
      const response = await fetch("/api/requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ business: String(data.get("business") || ""), website: String(data.get("website") || ""), email: String(data.get("email") || ""), extra: String(data.get("extra") || "") }) });
      if (!response.ok) { const result = (await response.json()) as { error?: string }; throw new Error(result.error || "Não conseguimos receber o pedido agora."); }
      form.reset(); setChecked(false); setState("sent");
    } catch (err) { setError(err instanceof Error ? err.message : "Tente novamente em alguns minutos."); setState("error"); }
  }

  return <main className="v-home" id="inicio">
    <header className="v-header v-wrap"><a href="#inicio" aria-label="Vistall, início"><Brand /></a><nav aria-label="Navegação principal"><a href="#modelos">O que faço</a><a href="#demonstracao">Demonstração</a><a href="#metodo">Como funciona</a><a href="/guia">Guia</a></nav><a className="v-header-cta" href="#contato">Iniciar projeto <ArrowUpRight size={17} aria-hidden="true" /></a></header>

    <section className="v-intro v-wrap" aria-labelledby="v-title"><div className="v-intro-glow" aria-hidden="true" /><div className="v-intro-meta"><span>ESTÚDIO INDEPENDENTE · BRASIL</span><span>SITES, REVISÕES & SISTEMAS WEB</span></div><div className="v-intro-center"><Asterisk className="v-intro-mark" /><h1 id="v-title">Vistall<span>.</span></h1><p className="v-intro-slogan">Um olhar atento. <em>Uma presença melhor.</em></p><p className="v-intro-lead">Reviso sites, crio páginas e desenvolvo sistemas web para pequenos negócios. Um trabalho independente, com apoio de IA e revisão humana.</p><a className="v-button v-button-dark" href="#modelos">Conheça o trabalho <ArrowDown size={18} aria-hidden="true" /></a></div><div className="v-intro-foot"><span>CLAREZA NO VISUAL. CUIDADO NO CÓDIGO.</span><span>ROLE PARA EXPLORAR <ArrowDown size={15} aria-hidden="true" /></span></div></section>

    <section className="v-statement" aria-label="Proposta da Vistall"><div className="v-wrap v-statement-inner"><span>VISTALL / O QUE FAÇO</span><h2>Pequenos ajustes.<br /><em>Ou novos caminhos.</em></h2><p>Da melhoria de uma página à criação de uma ferramenta digital: cada projeto começa pelo que você precisa resolver.</p><Asterisk className="v-statement-mark" /></div></section>

    <section className="v-services v-wrap" id="modelos"><div className="v-section-head"><div><span className="v-eyebrow">MODELOS DE ATUAÇÃO / 01</span><h2>Três formas de colocar<br /><em>sua ideia no ar.</em></h2></div><p>Você pode melhorar o que já existe, criar um site novo ou transformar uma tarefa recorrente em sistema.</p></div><div className="v-service-grid">{services.map((service) => <article className="v-service-card" key={service.number}><div className="v-card-top"><span>{service.number}</span><Asterisk /></div><div className="v-card-body"><p className="v-card-tag">{service.tag}</p><h3>{service.title}</h3><p>{service.description}</p><ul>{service.features.map((feature) => <li key={feature}><Check size={16} aria-hidden="true" />{feature}</li>)}</ul></div><div className="v-card-bottom"><p><strong>{service.price}</strong><span>{service.note}</span></p><a href={service.href}>{service.action}<ArrowUpRight size={18} aria-hidden="true" /></a></div></article>)}</div><p className="v-services-note">Revisão: preço fixo para uma página e até três ajustes combinados. Sites e sistemas: orçamento separado antes de qualquer contratação.</p></section>

    <section className="v-case" id="demonstracao"><div className="v-wrap"><div className="v-case-meta"><span className="v-eyebrow">O OLHAR DA VISTALL / 02</span><span>Demonstração ilustrativa, não projeto de cliente</span></div><div className="v-section-head v-case-head"><h2>Menos ruído.<br /><em>Mais clareza.</em></h2><p>Um título fácil de entender. Texto confortável de ler. Um caminho visível até o contato.</p></div><div className="v-demo-shell"><div className="v-demo-toolbar"><span><b>f.</b> Forma Contábil <small>/ marca fictícia</small></span><ToggleGroup type="single" value={demo} onValueChange={(value) => { if (value) setDemo(value); }} aria-label="Comparar demonstração" className="v-demo-tabs"><ToggleGroupItem value="before">Original</ToggleGroupItem><ToggleGroupItem value="after">Com ajustes</ToggleGroupItem></ToggleGroup></div><div className={improved ? "v-demo-page is-improved" : "v-demo-page"} aria-live="polite"><div className="v-demo-nav"><b>forma<span>®</span></b><span>CONTABILIDADE CONSULTIVA</span><span>MENU +</span></div><div className="v-demo-content"><div className="v-demo-copy"><span>PARA QUEM EMPREENDE</span><h3>Sua empresa cresce.<br />A gente cuida<br /><em>dos números.</em></h3><p>Contabilidade para pequenas empresas. Organize seus impostos e entenda os números do seu negócio.</p><span className="v-demo-link">Converse com um contador <ArrowUpRight size={17} aria-hidden="true" /></span></div><div className="v-demo-art"><small>UM NEGÓCIO.<br />NOVAS POSSIBILIDADES.</small><strong>f<span>.</span></strong><small>FORMA CONTÁBIL<br />CLAREZA PARA DECIDIR.</small></div></div><div className="v-demo-footer">CONTABILIDADE · PLANEJAMENTO · GESTÃO <span>EXEMPLO ILUSTRATIVO</span></div></div></div><div className="v-case-notes"><p><span>01</span><b>Hierarquia</b>{improved ? "Título em destaque e áreas organizadas." : "Informação principal sem destaque."}</p><p><span>02</span><b>Leitura</b>{improved ? "Texto com contraste e respiro." : "Texto pequeno e pouca separação."}</p><p><span>03</span><b>Contato</b>{improved ? "Chamada visível na composição." : "Link discreto no meio do conteúdo."}</p></div><p className="v-case-caption">A marca e a página acima são fictícias. O exemplo mostra uma mudança de apresentação; cada projeto real exige avaliação e escopo próprios.</p></div></section>

    <section className="v-method v-wrap" id="metodo"><div className="v-method-intro"><span className="v-eyebrow">MÉTODO & ESCOPO / 03</span><h2>Não precisa<br />começar <em>do zero.</em></h2><p>Na revisão, trabalho com o que já existe. Para um site ou sistema novo, defino o escopo com você antes de dar início.</p><div className="v-method-trust"><Asterisk /><span>Uma pessoa conduz o trabalho. Ferramentas de IA podem apoiar a execução, com revisão humana.</span></div></div><div className="v-method-steps"><div className="v-method-label"><span>NA REVISÃO DE R$ 250</span><span>UMA PÁGINA / ATÉ TRÊS AJUSTES</span></div>{steps.map((step, index) => <article key={step.title} className="v-step"><h3><button type="button" aria-expanded={openStep === index} aria-controls={`v-step-${index}`} onClick={() => setOpenStep(openStep === index ? null : index)}><span>0{index + 1}</span>{step.title}{openStep === index ? <Minus size={19} aria-hidden="true" /> : <Plus size={19} aria-hidden="true" />}</button></h3><div id={`v-step-${index}`} hidden={openStep !== index}><p>{step.text}</p></div></article>)}<p className="v-method-disclaimer">Sem promessa de vendas, conversões ou posição no Google. A entrega é o trabalho combinado no escopo.</p></div></section>

    <section className="v-contact" id="contato"><div className="v-wrap v-contact-grid"><div><span className="v-eyebrow">PROPOSTA & CONTATO / 04</span><h2>Vamos olhar<br /><em>de perto?</em></h2><p>Para uma revisão, envie seu site no formulário. Para criação de site ou sistema, escreva por e-mail e conte o que você precisa. O orçamento vem antes de qualquer pagamento.</p><div className="v-contact-price"><strong>R$ 250</strong><span>Revisão da página inicial<br />+ até três ajustes combinados</span></div><a className="v-mail" href={`mailto:${contactEmail}?subject=Projeto%20Vistall`}>{contactEmail} <ArrowUpRight size={17} aria-hidden="true" /></a></div><div className="v-form-panel">{state === "sent" ? <div className="v-success" role="status"><span className="v-success-icon"><Check size={26} /></span><h3>Recebemos seu pedido.</h3><p>Para confirmar a revisão de R$ 250, conclua o pagamento pelo Mercado Pago. No checkout, confira o nome cadastrado da conta de pagamento antes de concluir.</p><Button asChild className="v-submit"><a href={paymentUrl} target="_blank" rel="noopener noreferrer">Ir para o pagamento <ArrowUpRight size={18} /></a></Button><p className="v-form-note">A execução depende do pagamento, do escopo e do acesso necessário. Se não pudermos realizar o pedido nesse escopo, combinaremos o estorno.</p></div> : <form onSubmit={submit}><div className="v-form-head"><span>PEDIDO DE REVISÃO</span><span>01 / 03</span></div><div className="v-field"><label htmlFor="business"><span>01</span> Nome do negócio</label><Input id="business" name="business" required maxLength={100} autoComplete="organization" placeholder="Como seu negócio se chama?" /></div><div className="v-field"><label htmlFor="website"><span>02</span> Endereço do site</label><Input id="website" name="website" required type="url" maxLength={300} placeholder="https://seusite.com.br" /></div><div className="v-field"><label htmlFor="email"><span>03</span> Seu e-mail</label><Input id="email" name="email" required type="email" maxLength={200} autoComplete="email" placeholder="voce@empresa.com.br" /></div><div className="v-trap" aria-hidden="true"><label htmlFor="extra">Deixe em branco</label><Input id="extra" name="extra" tabIndex={-1} autoComplete="off" /></div><label className="v-agree" htmlFor="agree"><Checkbox id="agree" checked={checked} onCheckedChange={(value) => setChecked(value === true)} /><span>Entendi que a revisão começa com uma checagem automática e que os ajustes serão confirmados antes da execução.</span></label>{error && <p className="v-error" role="alert">{error}</p>}<Button type="submit" disabled={!checked || state === "sending"} className="v-submit">{state === "sending" ? "Enviando…" : "Enviar meu site"}<ArrowUpRight size={19} aria-hidden="true" /></Button><p className="v-form-note">Seus dados serão usados para avaliar e atender este pedido.</p></form>}</div></div></section>

    <footer className="v-footer"><div className="v-wrap"><div className="v-footer-top"><Brand /><p>Um olhar atento.<br /><em>Uma presença melhor.</em></p><a href="#inicio">Voltar ao início ↑</a></div><div className="v-footer-bottom"><span>VISTALL © 2026</span><p><a href="/guia">Guia prático</a> · <a href="/avaliar">Avalie seu site</a> · <a href={`mailto:${contactEmail}`}>{contactEmail}</a><br />Atendimento remoto no Brasil. Vistall é um estúdio independente operado por uma pessoa. Ferramentas de IA podem ser usadas como apoio, sempre com revisão humana. Pagamentos são processados pelo Mercado Pago; confira os dados do recebedor antes de concluir. Não há garantia de resultados em vendas ou buscas. Para tratar dos seus dados, escreva para o e-mail de contato.</p></div></div></footer>
  </main>;
}
